### ISSUE TITLE
Update Phore wallet logos

### ISSUE THREAD

**Issue by tohsnoom** [phoreproject/Phore#13]
Update Phore wallet with new Phore logos.

**Comment by ghost** [comment]
See pull request #18.

![](https://i.imgur.com/NskX5IT.png)
![](https://i.imgur.com/c4bpmUo.png)
![](https://i.imgur.com/A3riERW.png)
![](https://i.imgur.com/6Fdvv8m.png)

**Comment by meyer9** [comment]
Completed
