### ISSUE TITLE
Compiling error at leveldb

### ISSUE THREAD

**Issue by ghost** [phoreproject/Phore#135]
This issue tracker is only for technical issues related to Phore Core.
General Phore questions and/or support requests and are best directed to the [Phore Discord](https://discord.gg/sbgdcdv).

#### If so, please list the steps to reproduce below:

All is running fine, only the build from the leveldb I receive this error.

### Actual behavior

make[1]: Entering directory '/home/s/src/src'
make[2]: Entering directory '/home/s/src/src'
Building LevelDB ...
make[3]: Entering directory '/home/s/src/src/leveldb'
make[3]: *** No rule to make target 'libmemenv.a'.  Stop.
make[3]: Leaving directory '/home/s/src/src/leveldb'
Makefile:8630: recipe for target 'leveldb/libmemenv.a' failed
make[2]: *** [leveldb/libmemenv.a] Error 2
make[2]: Leaving directory '/home/s/src/src'
Makefile:8140: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/s/src/src'
Makefile:681: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Phore Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
1.60
### Machine specs:
- OS: Ubuntu 18.04
- CPU: 4 core
- RAM: 8gb
- Disk size: 80gb
- Disk Type (HD/SDD): ssd

### Any extra information that might be useful in the debugging process.
chmod 755 src/leveldb/build_detect_plattform I did

**Comment by KolbyML** [comment]
Ok so the issue is you are not compiling Phore you are forking it for one. This doesn't appear to be a Phore related issue. Maybe you should check what you changed ;)
Am 67% sure

**Comment by KolbyML** [comment]
Even if you were compiling Phore which you are most likely not. Those 5 lines wouldn't do much help as where it says error isn't where it says the error in most cases

**Comment by ghost** [comment]
The problem was nimble fingers and a tired brain.

Am Sa., 19. Jän. 2019, 09:49 hat Kolby Moroz <notifications@github.com>
geschrieben:

**Comment by tohsnoom** [comment]
Sounds like we can close this, if you have further issues with Phore let us know.
