### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by johnpaul199812** [phoreproject/Phore#190]
No response when I put in make airdrop file
Is it normal?
How do I solve that
![IMG_20210819_001138_980](https://user-images.githubusercontent.com/42779023/129983789-ab3225d5-a4c3-4b6d-ab26-1163cbbdd35b.jpg)
![IMG_20210819_000849_917](https://user-images.githubusercontent.com/42779023/129983822-788cbf77-024f-492c-bef0-5378d3a2cef5.jpg)

### Machine specs:
- OS: windows 10 pro
- CPU: 1.8
- RAM:4
- Disk size:320
- Disk Type (HD/SDD):

**Comment by wqking** [comment]
It's not a problem. If it creates the correct output file, 'airdrop.txt' in your case, then it works successfully.

**Comment by johnpaul199812** [comment]
So how do I make it to create the correct output file

**Comment by wqking** [comment]
In you case the output file is airdrop.txt, did you find it?

**Comment by johnpaul199812** [comment]
You mean in my pc files?
I just used that,
Can I use another file name

**Comment by johnpaul199812** [comment]
![image](https://user-images.githubusercontent.com/42779023/130132883-74d3c048-3834-4513-8b2b-4de800ac0b45.png)
this correct right?

**Comment by johnpaul199812** [comment]
![image](https://user-images.githubusercontent.com/42779023/130134710-21edce23-5c7d-4618-b4da-d5d7a8944ce9.png)

**Comment by johnpaul199812** [comment]
what could be wrong

**Comment by tohsnoom** [comment]
@johnpaul199812 It looks like the correct format for the airdrop file.

In terms of the Pre-Airdrop Summary being blank, what PHR balances did you have as of the first airdrop date? Can you provide me with a PHR address in your airdrop file that had a balance as of the first airdrop date? You can find me in the Phore Discord (Michael T. | Phore.io) using the colored names on the right hand side and send me a DM if you prefer to keep the information private, and we can help you troubleshoot.

**Comment by johnpaul199812** [comment]
my balance is zero 
its a new wallet 
i just found out about the project
give me your discord username
