### ISSUE TITLE
Phore -> Phore-old is a bad pattern

### ISSUE THREAD

**Issue by kx9x** [phoreproject/Phore#2]
Stripping out the previous repo to Phore-old and leaves the current issues and contribution history in the Phore-old repo and not in the new Phore repo. 

Phore-old should have been rebased (with removing the initial commit) from the original fork point (some time in September or so) if we wanted to properly show the original fork from PIVX. Then we could have merged the more recent changes we wanted after completing the rebase. IMO, it would be worthwhile to go ahead and do this even though it might be a pain. It would also give us a chance to squash commit history and apply a better style to commit messages.

**Comment by meyer9** [comment]
Unfortunately, this would still not solve the problem of having the "from from PIVX-Project/PIVX" at the top. I'll look into this though.

**Comment by tohsnoom** [comment]
I think at this point we are pretty set on using the new repository. I understand the concern, and Phore-old will be kept around in archived form if we ever need to refer to it.
