### ISSUE TITLE
Merge CHECKLOCKTIMEVERIFY

### ISSUE THREAD

**Issue by meyer9** [phoreproject/Phore#25]
Merge this commit from the Bitcoin upstream.

https://github.com/petertodd/bitcoin/commit/ab0f54f38e08ee1e50ff72f801680ee84d0f1bf4

**Comment by wqking** [comment]
I think this conflicts with Bitcoin core.
In Bitcoin core,
SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY = (1U << 9),
https://github.com/bitcoin/bitcoin/pull/7524/commits/53e53a33c939949665f60d5eeb82abbb21f97128

In the repo in this issue,
SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY = (1U << 5)
https://github.com/petertodd/bitcoin/commit/ab0f54f38e08ee1e50ff72f801680ee84d0f1bf4

I think we should merge all changes from Bitcoin core.

**Comment by meyer9** [comment]
just set it to the next available flag.

merging all commits from BTC Core will take an insane amount of time

**Comment by cranberriez** [comment]
Done in 077df26b3add1ab9eda0de59db29d3c1b99e286d
