### ISSUE TITLE
Staking issue

### ISSUE THREAD

**Issue by Multielio** [phoreproject/Phore#3]
### Actual behavior
Staking active but I am not getting rewards anymore after sending more phr to my main staking address. 
I did not get phr during:  2 * the normal reward time
I restarted my server and phore wallet, I am waiting for the next rewards to see if it fixed the issue.

### What version of Phore Wallet are you using?
Lasted version of Phore Wallet
### Machine specs:
- OS: Ubuntu Xenial
- Disk size: 50 G
- Disk Type (HD/SDD):  SSD

**Comment by meyer9** [comment]
How much PHR are you staking?

**Comment by meyer9** [comment]
stale issue
