### ISSUE TITLE
raspberry/arm wallet  ...

### ISSUE THREAD

**Issue by trnepalla** [phoreproject/Phore#38]
hi,

i think the raspberry /arm wallet 
actually is not compatibile with armv6l architecture (an old raspberry pi 1) ..
cause i'im getting an 'illegal istruction' at execution.

could you confirm?

thanks.

**Comment by KolbyML** [comment]
Could you give the whole log in a pastebin it is hard to tell a problem from nothing. You would need to compile libdb4.3 i believe it is from source.  The point is could you give some more infomation on your issue like the whole log. I mean copy and paste the whole compile message.

**Comment by KolbyML** [comment]
http://blog.pryds.eu/2014/06/compile-bitcoin-core-on-raspberry-pi.html This may work but the thing is the raspberry pi 1 doesn't have a lot of power now a days so support is lacking hope this helps

**Comment by trnepalla** [comment]
yes, i managed to smootly compile phore from source (just be patient ;) ..  

what i said is that i think the raspberry/arm binaries of the wallet ready to download from the site are not compatibile with che old raspberry arch (armv6l) .. which is anyway the same arch of a new raspberry zero w.   thanks.
