### ISSUE TITLE
SegWit branch: sendrawtransaction doesn't work?

### ISSUE THREAD

**Issue by wqking** [phoreproject/Phore#40]
The test cast test_send_raw_transaction in [temp.py](https://github.com/wqking/Phore/blob/0fbe41930649a290ca46fb5df92f3285e89996eb/test/temp.py) doesn't work because sendrawtransaction returns -25 verify error.

The same can be reproduced on command line.
We need to check if it's a problem in the core code or there is wrong in the test steps.

Command line steps:
```
// Start two nodes
phored -regtest -datadir=Folder0
phored -regtest -datadir=Folder1

// Node0 mine 101 blocks
phore-cli -regtest -datadir=Folder0 setgenerate true 101

// Get a node0 unspent txid
phore-cli -regtest -datadir=Folder0 listunspent
// Now we get a txid f8170a80a479d2d91dd08d93886018c21feef3143d00b5bcb5b2f8d26408722e

// Get a new address on node1
phore-cli -regtest -datadir=Folder1 getnewaddress

// Create raw transaction on node0
phore-cli -regtest -datadir=Folder0 createrawtransaction '[{ "txid": "f8170a80a479d2d91dd08d93886018c21feef3143d00b5bcb5b2f8d26408722e","vout" : 0 }]' '{"8idfiRJ9FTyV6esqT4AQfDFUv5L3wRPLnA": 100 }'
// Now we get transaction 01000000012e720864d2f8b2b5bcb5003d14f3ee1fc2186088938dd01dd9d279a4800a17f80000000000ffffffff0100e40b540200000017a9142e2f845306f129b4772355439020f5aa0afaaff08700000000

// Sign the transaction on node0
phore-cli -regtest -datadir=Folder0 signrawtransaction 01000000012e720864d2f8b2b5bcb5003d14f3ee1fc2186088938dd01dd9d279a4800a17f80000000000ffffffff0100e40b540200000017a9142e2f845306f129b4772355439020f5aa0afaaff08700000000
// We got
{
  "hex": "01000000012e720864d2f8b2b5bcb5003d14f3ee1fc2186088938dd01dd9d279a4800a17f8000000004847304402200897657e4c8ad860291e20f65dfe95b52b21be0667d69ec546d89ca2968cc2b802204bdb203a4734757ba6ea15bd0236fd9d7635d1da7b5d49efa0711e89915d97f701ffffffff0100e40b540200000017a9142e2f845306f129b4772355439020f5aa0afaaff08700000000",
  "complete": true
}

// Send the transaction
phore-cli -regtest -datadir=Folder0 sendrawtransaction 01000000012e720864d2f8b2b5bcb5003d14f3ee1fc2186088938dd01dd9d279a4800a17f8000000004847304402200897657e4c8ad860291e20f65dfe95b52b21be0667d69ec546d89ca2968cc2b802204bdb203a4734757ba6ea15bd0236fd9d7635d1da7b5d49efa0711e89915d97f701ffffffff0100e40b540200000017a9142e2f845306f129b4772355439020f5aa0afaaff08700000000

// Got error: error: {"code":-25,"message":""}
```

**Comment by meyer9** [comment]
Possibly a problem with SegWit not being enabled on regtest?

**Comment by wqking** [comment]
No, the bug is nothing with SegWit, it's just normal non-SwgWit raw transaction.

**Comment by meyer9** [comment]
Well, this: `8idfiRJ9FTyV6esqT4AQfDFUv5L3wRPLnA` is a SegWit address.

I think it might have to do with signrawtransaction not supporting SegWit.

---

https://bitcoin.stackexchange.com/questions/59443/signrawtransaction-of-a-p2sh-p2wpkh-spend-seems-to-be-broken

Looks like the problem is that signrawtransaction needs an amount parameter now.

**Comment by wqking** [comment]
OK, I found the reason. AcceptToMemoryPool rejected the transaction due to insane fees. There were 2500 coins in that address and I was trying to send 100, the remaining 2400 is too large to be fees.
So this is not a bug. I will close it.

**Comment by wqking** [comment]
Reopen this issue.
After changing the amount in the original message from 100 to 2499.999, sendrawtransaction successes and returned the txid, but after node0 mined a new block to confirm the new transaction, the new block doesn't include the new transaction (it only includes the coinbase), and node1 balance is still 0.
And temp.py doesn't have the "insane fees" error because the second parameter of sendrawtransaction which means any fees are OK.
There is no error messages in debug.log.
Also I doubt this bug is related to SegWit, the address starts with letter '8' can be either a P2SH or SegWit address.

**Comment by meyer9** [comment]
This doesn't seem to be happening any more.
