### ISSUE TITLE
Port detection of masternode.conf misbehavior

### ISSUE THREAD

**Issue by liray-unendlich** [phoreproject/Phore#47]
### Describe the issue
Port detection of masternode.conf denies port 11771 for mainnet.
#### If so, please list the steps to reproduce below:
1. Use default line of masternode.conf for masternode configuration.
```
mn1 127.0.0.2:11771 93HaYBVUCYjEMeeH1Y4sBGLALQZE1Yc1K64xiqgX37tGBDQL8Xg 2bcd3c84c84f87eaa86e4e56834c92927a07f9e18718810b92e0d0324456a67c 0
```
2. Start phore-qt-1.3.0.exe
3. Popup
![image](https://user-images.githubusercontent.com/15893314/41524282-f105ad46-7317-11e8-92e4-fe0a6ba88e34.png)

### Expected behavior
Port detection should pass this line of masternode configuration

### Actual behavior
Port detection of masternode.conf denied port 11771 for mainnet

### Screenshots.
![image](https://user-images.githubusercontent.com/15893314/41524282-f105ad46-7317-11e8-92e4-fe0a6ba88e34.png)

### What version of Phore Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
Official pre-released binary, v1.3.0 for Windows x64
https://github.com/phoreproject/Phore/releases/download/v1.3.0/phore-1.3.0-win64.zip
### Machine specs:
- OS: Windows8.1 x64
- CPU: i5-4570
- RAM: 12GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

**Comment by meyer9** [comment]
Only occurs on Windows. Possibly due to line endings.

**Comment by meyer9** [comment]
```cpp
if (Params().NetworkID() == CBaseChainParams::MAIN) {
            if (CService(ip).GetPort() != 11771) {
                strErr = _("Invalid port detected in masternode.conf") + "\n" +
                         strprintf(_("Line: %d"), linenumber) + "\n\"" + line + "\"" + "\n" +
                         _("(must be 11771 for mainnet)");
                streamConfig.close();
                return false;
            }
        } else if (CService(ip).GetPort() == 11771) {
            strErr = _("Invalid port detected in masternode.conf") + "\n" +
                     strprintf(_("Line: %d"), linenumber) + "\n\"" + line + "\"" + "\n" +
                     _("(11771 could be used only on mainnet)");
            streamConfig.close();
            return false;
        }
```

The failing code must be inside here:
```cpp
if (CService(ip).GetPort() != 11771) {
                strErr = _("Invalid port detected in masternode.conf") + "\n" +
                         strprintf(_("Line: %d"), linenumber) + "\n\"" + line + "\"" + "\n" +
                         _("(must be 11771 for mainnet)");
                streamConfig.close();
                return false;
            }
```

**Comment by meyer9** [comment]
Fixed.
