### ISSUE TITLE
dumpprivkey doesn't return private key

### ISSUE THREAD

**Issue by liray-unendlich** [phoreproject/Phore#48]
### Describe the issue
Command "dumpprivkey" doesn't work for legacy address.
### Can you reliably reproduce the issue?
Yes.
#### If so, please list the steps to reproduce below:
1. getnewaddress
2. dumpprivkey **GENERATED_ADDRESS**
3. Get an error "Address does not refer to a key (code -3)

### Expected behavior
"dumpprivkey" should return private key of input address

### Actual behavior
"Address does not refer to a key (code -3)" error was returned

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![2018-06-26 19 37 46](https://user-images.githubusercontent.com/15893314/41906376-aace3138-7978-11e8-9302-eb66a23cf18b.png)

### What version of Phore Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
v1.3.0-rc2(phore-1.3.0-osx-unsigned.dmg)
v1.3.0-rc2(phore-1.3.0-win64.zip)

### Machine specs:
- OS: Windows8.1/OSX(10.13.4)
- CPU: i5/i5
- RAM:12GB/8GB
- Disk size: 256GB/256GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by meyer9** [comment]
fixed.
